name: KARI
channels:
  - defaults
dependencies:
  - pip:
    - h5py==2.10.0
    - imageio==2.9.0
    - numpy==1.20.0
    - opencv-python==4.5.3.56
    - pillow==8.3.1
    - tensorflow==2.4.0
    - tqdm==4.62.0
    - matplotlib
    - spectral
    - snappy